export const GENERATE_NEW_ARRAY = 'GENERATE_NEW_ARRAY';

export const BUBBLE_SORT= 'BUBBLE_SORT'
export const SELECTION_SORT= 'SELECTION_SORT'
export const INSERTION_SORT= 'INSERTION_SORT'
export const MERGE_SORT= 'MERGE_SORT'
export const QUICK_SORT= 'QUICK_SORT'
export const HEAP_SORT= 'HEAP_SORT'